In [1]:
def rn(n):
    sign= -1 if n <0 else 1
    n=abs(n)
    rev=0
    while n>0:
        rev= rev*10+n%10
        n//=10
    return sign * rev
print(rn(-987))

-789

In [3]:
def tn(nums):
    t=0
    for n in nums:
        t+=n
    return t

print(tn([3,4,5,3]))

15

In [6]:
def ev(nums):
    return [num for num in nums if num%2==0]
print(ev([1,2,3,4,5,6]))

[2, 4, 6]

In [12]:
def freq(nums):
    d={}
    for n in nums:
        d[n]=d.get(n,0)+1
    return d

print(freq([2,3,43,3,5]))
print(freq(sorted([2,3,43,3,5])))

{2: 1, 3: 2, 43: 1, 5: 1}
{2: 1, 3: 2, 5: 1, 43: 1}

In [23]:
def rev(s):
    return " ".join(s.split()[::-1])

print(rev("hello world python"))

def vd(d):
    return d[::-1]

print(vd("hello world python"))

python world hello
nohtyp dlrow olleh

In [24]:
def ce(a,b,c):
    return list(set(a)&set(b)&set(c))

print(ce([1,2,3,4], [2,3,5], [2,3,6]))

[2, 3]

In [28]:
def cd(n):
    c=0
    while n>0:
        c+=1
        n//=10
    return c

print(cd(3245))

4

In [31]:
def co(nums,x):
    return str(nums).count(str(x))

print(co(2334,9))

0

In [37]:
def rs(s,k):
    k%=len(s)
    return s[-k:]+s[:-k]

print(rs("ritessd",4))

essdrit

In [42]:
def cap(s):
    return " ".join(word.capitalize() for  word in s.split())

print(cap("hj g"))

Hj G

In [48]:
def f_d(nums):
    seen=set()
    for num in nums:
        if num in seen:
            return num
        seen.add(num)
    return None

print(f_d([2, 3, 4, 4, 3]))

4

In [53]:
def ss(nums):
    nums=list(set(nums))
    nums.sort()
    return nums[1]

print(ss([2,4,5,6,1,3]))

2

In [55]:
def cw(s):
    return len(s.split())

print(cw("dfddf s  s "))

3

In [57]:
def po2(n):
    return n>0 and (n&(n-1))==0

print(po2(4))

True

In [3]:
import math
def power_of_two(n):
    if n > 0 and (n & (n - 1)) == 0:
        return int(math.log2(n))
    return -1

print(power_of_two(16))

4

In [1]:
def single_num(nums):
    res = 0
    for num in nums:
        res ^= num
    return res

print(single_num([2,3,2,4,4])   )

3

In [4]:
class Dog:
    def sound(self):
        print("Bark")

class Cat:
    def sound(self):
        print("Meow")

for animal in [Dog(), Cat()]:
    animal.sound()

Bark
Meow

In [5]:
class Animal:
    def speak(self):
        print("Animal speaks")

class Dog(Animal):
    pass

d = Dog()
d.speak()

Animal speaks

In [6]:
from abc import ABC, abstractmethod

class Vehicle(ABC):

    @abstractmethod
    def start(self):
        pass

class Car(Vehicle):
    def start(self):
        print("Car starts with key")

class Bike(Vehicle):
    def start(self):
        print("Bike starts with kick")

c = Car()
c.start()

Car starts with key

In [9]:
def mz(arr):
    j=0
    for i in range(len(arr)):
        if arr[i]!=0:
            arr[j],arr[i]=arr[i],arr[j]
            j+=1
    return arr
    
print(mz([2,2,3,4,0,3,0,3]))

[2, 2, 3, 4, 3, 3, 0, 0]

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv(r"C:\Users\ACER\Downloads\AirPassengers.csv")

In [11]:
df.head()

     Month  #Passengers
0  1949-01          112
1  1949-02          118
2  1949-03          132
3  1949-04          129
4  1949-05          121

In [14]:
df.shape

(144, 2)

In [15]:
df.columns

Index(['Month', '#Passengers'], dtype='object')

In [16]:
df.dtypes

Month          object
#Passengers     int64
dtype: object

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Month        144 non-null    object
 1   #Passengers  144 non-null    int64
dtypes: int64(1), object(1)
memory usage: 2.4+ KB

In [18]:
df.describe()

       #Passengers
count   144.000000
mean    280.298611
std     119.966317
min     104.000000
25%     180.000000
50%     265.500000
75%     360.500000
max     622.000000

In [19]:
df.isnull().sum()

Month          0
#Passengers    0
dtype: int64

In [1]:
sq = lambda x:x*x
print(sq(5))

25

In [4]:
sq= [x*x for x in range(5)]
print(sq)

[0, 1, 4, 9, 16]

In [11]:
def gen():
    yield 1
    yield 2

g = gen()
print(next(g))
print(next(g))

1
2

In [13]:
for i, val in enumerate ([10,20,30]):
    print(i,val)

0 10
1 20
2 30

In [14]:
 try:
    x = 10 / 0
except ZeroDivisionError:
    print("Error occurred")
finally:
    print("This will always execute")

Error occurred
This will always execute